[project]
name = "automated-dart-scorer"
version = "0.1.0"
description = "A smart, automated dart scoring app that tracks throws, calculates scores in real time, and simplifies game management for dart players."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
